### ISSUE TITLE
Support configuring the client from environment variables

### ISSUE THREAD

**Issue by ahmed-mez** [unbounce/clojure-dogstatsd-client#15]
All of the official Datadog dogstatsd clients can now be configured via standard environment variables.  As the maintainer of the closure dogstatsd library, could you port the same functionality to this client?  We would prefer that configuration be consistent across client libraries.

Sample changes from the Go implementation can be found here: https://github.com/DataDog/datadog-go/pull/78

Let me know if you have any questions about the code or the feature more generally.

Thanks,

Ahmed

**Comment by rymndhng** [comment]
Hey, sorry for the slow reply! I only noticed I had missed this email. 

Yes, that's very doable. One thing to note is that this library is a wrapper over https://github.com/DataDog/java-dogstatsd-client. It looks like the latest release of the java client is `2.7`, which does not yet support the env vars. 

I'd prefer to put explicit support/test/documentation in this library *after* the Java client is updated -- this gives us an option to use the resolution strategy from the underlying library instead of duplicating functionality.

**Comment by hden** [comment]
It does now.
https://github.com/DataDog/java-dogstatsd-client/releases/tag/v2.8

**Comment by rymndhng** [comment]
Thanks for the heads up! 0.6.0 supports this now!
